var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                           o      xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                                    o o      xx                  x!!!x          ",
   "                                                                 x!!!x          ",
   "            yyyy                   yyyyy                         x!!!x          ",
   "             yyyyy                   yy                            v         x  ",
   "  xx                                      o o        hhhhhh                  x  ",
   "  x                        o                         h hh h                o x  ",
   "  x                                      xxxxx                             o x  ",
   "  x       xxxxxxxx      o     o                                              x  ",
   "  x       x      x                                               xxxxx       x  ",
   "  x  @    x      x                                                           x  ",
   "  xxxxxxxxx      xxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxx     xxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                              xxxxxx!!!xxxxx                             xxxxx!x  ",
   "                                                              xxxxx!!!!!xxxxx                                x!x  ",
   "                                xxxxxxxxxxxxxxxxxxxx         xxxxxxxx!xxxxxxxx                               x!x  ",
   "                                x!!!!!!!!!!!!!!!!!xx         xxxx    o    xxxx                               x!x  ",
   "                                x!!!xxxxxxxxxxxxx!!x   o     x      xxx                  xxx      o   o   o  x!x  ",
   "                                x!!!x           xx!x   x           o   o           xxx          |           xx!x  ",
   "                                x!!!x            x!x       xxx               xxx             |xxxxxxxxxxxxxxx!!x  ",
   "       s                        x!!!x            xvx         x     x   x                    !!!!!!!!!!!!!!!!!!xx  ",
   "      xxx                       x!!!x                        xx  |   |   |  xx             xxxxxxxxxx v xxxxxxxx  ",
   "                                x!!!x                       xxxx!!!!!!!!!!!xxxx          v                        ",
   "                                x!!!x                     xxxxxxxx!!!!!!xxxxxxxx                                  ",
   "            xxx                 x!!!x          x     x         xxxxxxxxxxxxxxx   xxx         xxx                  ",
   "                                x v x          x     x                             x         x                    ",
   "                                               x     x                             x         x                    ",
   "                                               xo    x                             xx        x                    ",
   "       xxx                                     xx    x                             x        ox                    ",
   "      ==                                       x     x      o  o     x   x         x        xx                    ",
   "                              xxx   xxx        x     x               x   x         x         x                    ",
   "                                x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x    xx    x    xx               x   x   x               x        s           ",
   "        xxx  x         x        x   x          x     x               x   x   x                      xxxxx         ",
   "    @        x    o    x        x   x    |     x     x  xx           x   xxxxx   xxxxxx      xxx                  ",
   "  xxxxx      x   xxx   x       xx o xx!!!!!!!!!x     x               x o         x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!!!!     xxxxxxxxxxxxxxxx o   o xx                    ",
   "!!!!x x!!!!!!xx        x!!!!!x    o                 xx!!!!!!!!!!                    xx  o  xx                     ",
   "!!!!x x!!!!!!x    s   xx!!!!!x                     xx!!!!!!!!!!!                    xxx!!!xxx                     ",
   "!!!!x x!!!!!!x    x    x!!!!!xx       xxxxxxxxxxxxxx!!!!!!!!!!!!                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                          o                                                                                   ",
   "                          o                                                                                   ",
   "                         xxx   xxxx                                                                           ",
   "               o                      xxx                                                                     ",
   "           o       o      =  |  =                                                                             ",
   "    xxxxxxxxxxxxxxxxxx                    xxx                                                                 ",
   "    x!!!!!!!!!!!!!!!!x                                       xxx                                              ",
   "    x              v                                                                                          ",
   "    x                                                                                                         ",
   "    x                                                                                                         ",
   "    x                                                                                                         ",
   "    x                                                                                                         ",
   "    x    o       o                         xxxxxxxxxxx    xxxxx                                               ",
   "    x   xxx v   xxx   xxxxxx        xxxxxxx                xx                                                 ",
   "    x         !!!!!!!!!!!x          x             v          xxx                                              ",
   "    xx        xxxxxxxxxxxx          xo                         xxxxxxxxx                                      ",
   "              x                     x      xxxxx    xxxxx      x!!!!!!!x                                      ",
   "       xx     x                     xx     x                       v                                          ",
   "       xxx                          x      x                                                                  ",
   "                                    x     xx     xxx                                 xxxx |        s          ",
   "                                    x      x                       o                             xxxxx        ",
   "         xxx                        x                xxx    =    xxxx                                         ",
   "              o                          o           x      x                    xxxx                         ",
   "             xxx                       xxxx          x                                                        ",
   "                                                     x  xxx           xxxx                                    ",
   "                   |  xxx          xxx               x!!!!!!!!!!!!!!!!!!!x   x                                ",
   "    xxxxxxxxxx                  o  x                  x!!!!!!!!!!!!!!!!!x                                     ",
   "    x   o    x             | xxxxxxx                   x!!!!!!!!!!!!!!!x        x                             ",
   "    x                                                   xxxxxxxxxxxxxxx                                       ",
   "    x   @            xxx                                                              o                       ",
   "    xxxxxxxxxxxxx                                                                     x                   x   ",
   "                                                                             x                        o   x   ",
   "                                                                     o                              o   o x   ",
   "                                                                     x                             xxxxxxxx   ",
   "                                                                                xx  x   x    x  |xxxxxx       ",
   "                                                                                xx!!!!!!!!!!!!xx              ",
   "                                                                                xxxxxxxxxxxxxxxx              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                          YOU WIN!                                                            ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
